### ISSUE TITLE
Feature Request: eGFR and BSA?

### ISSUE THREAD

**Issue by billdenney** [jackwasey/physiology#1]
I was looking for a package to do similar.  Would you be interested in the following:

* Estimated glomerular filtration rate (eGFR)?
* Additional body surface area (BSA) calculation equations?

Also, for eGFR, the preferred calculation method varies by population (child vs adult, value <60 mL/min/1.73 m^2, >=60 mL/min/1.73 m^2).  What I've done in my initial code is add selectors that match the population to the calculation.  Give sufficient demographic information, and it will automatically select the best calculation method.

**Comment by jackwasey** [comment]
Excellent idea: would be happy to accept a pull request.

**Comment by billdenney** [comment]
While working on the PR, I found https://github.com/jackwasey/physiology/blob/master/man-roxygen/height_m.R

It indicates that `height_m` is a scalar.  What I'm working toward will take a vector.  Is the scalar limitation accurate?  (If so, I'll use my own text for `height_m`; if not, I'll update it with another PR.)

**Comment by billdenney** [comment]
BSA suggested; eGFR will probably come tomorrow.

**Comment by billdenney** [comment]
If PRs #2 and #3 are accepted, that would close this issue.

**Comment by billdenney** [comment]
Thanks!
